# Generated by Django 5.2 on 2026-02-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="instructor_notified",
            field=models.BooleanField(default=False),
        ),
    ]
