# Generated by Django 5.2.2 on 2026-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="instructor_notified",
            field=models.BooleanField(default=False),
        ),
    ]
